-- AlterTable
ALTER TABLE "User" ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "activity_level" DROP NOT NULL,
ALTER COLUMN "age" DROP NOT NULL,
ALTER COLUMN "calorie_goal" DROP NOT NULL,
ALTER COLUMN "carbs_goal" DROP NOT NULL,
ALTER COLUMN "consent_date" DROP NOT NULL,
ALTER COLUMN "fat_goal" DROP NOT NULL,
ALTER COLUMN "gender" DROP NOT NULL,
ALTER COLUMN "height" DROP NOT NULL,
ALTER COLUMN "protein_goal" DROP NOT NULL,
ALTER COLUMN "weight" DROP NOT NULL;
